version: '3.7'
services:
  app:
    container_name: main
    build: 
      context: .
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes: 
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: